service: toplast-api

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(env.yml):${self:provider.stage}}

plugins:
  - serverless-bundle
  - serverless-offline

package:
  individually: true

functions:
  hello:
    handler: src/hello/hello.handle
    events:
      - http:
          path: hello
          method: get
