service: toplast-api

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
